data_processing:
  test_size: 0.2
  random_state: 42
  input_columns:
    - before_exam_125_Hz
    - before_exam_250_Hz
    - before_exam_500_Hz
    - before_exam_1000_Hz
    - before_exam_2000_Hz
    - before_exam_4000_Hz
    - before_exam_8000_Hz
  output_columns:
    - after_exam_125_Hz
    - after_exam_250_Hz
    - after_exam_500_Hz
    - after_exam_1000_Hz
    - after_exam_2000_Hz
    - after_exam_4000_Hz
    - after_exam_8000_Hz

training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  units: 128
  dropout_rate: 0.2